### ISSUE TITLE
> It would be nice if a subrange or even a specific ip would return the most specific announcement that it is in.

### ISSUE THREAD

**Issue by Dino1981** [bgptools/fgbgp#1]
> It would be nice if a subrange or even a specific ip would return the most specific announcement that it is in.

afaik this is already the case for specific IPs but if you specify the subnet length, then it won't. (I think this is intentional)

_Originally posted by @bitcynth in https://github.com/bgptools/issues/issues/10#issuecomment-877051687_

**Comment by benjojo** [comment]
I don't understand the issue you are reporting here. Closing until I have
more information
